export const siteConfig = {
  name: "Salmara Ayurveda",
  url: "https://salmara.com",
  logo: "/salamara_icon.jpg",
  contact: {
    phone: "+91-9353436373",
    email: "customercare@salmara.com",
    whatsapp: "919353436373",
  },
  social: {
    facebook: "https://www.facebook.com/share/18GfJXco63/?mibextid=wwXIfr",
    instagram: "https://www.instagram.com/salmara_ayurveda?igsh=ejhxdHA0NGFoeWNj",
    youtube: "https://www.youtube.com/@salmara_ayurveda",
  },
  clinics: [
    {
      id: 1,
      name: "Salmara Ayurveda - Bangalore",
      address: "Bangalore - Rajajinagar / ಬೆಂಗಳೂರು - ರಾಜಾಜಿನಗರ",
      streetAddress: "Rajajinagar",
      city: "Bengaluru",
      state: "Karnataka",
      zip: "560010",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/1Eo81kBhyswaBi1W6",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Pain Relief", "Liver Detox"]
    },
    {
      id: 2,
      name: "Salmara Ayurveda - Puttur",
      address: "Puttur - D.K / ಪುತ್ತೂರು - ದ.ಕ",
      streetAddress: "Salmara",
      city: "Puttur",
      state: "Karnataka",
      zip: "574201",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/3oEEbpH7h8w8Uyx2A",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Women's Wellness", "Digestion"]
    },
    {
      id: 3,
      name: "Salmara Ayurveda - Mysore",
      address: "Mysore - Saraswatipuram / ಮೈಸೂರು - ಸರಸ್ವತೀಪುರಂ",
      streetAddress: "Saraswatipuram",
      city: "Mysuru",
      state: "Karnataka",
      zip: "570009",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/XRr29xvW9GJF3QDH6",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Immunity", "Skin Care"]
    },
    {
      id: 4,
      name: "Salmara Ayurveda - Hubli",
      address: "Hubli - Vidyanagar / ಹುಬ್ಬಳ್ಳಿ - ವಿದ್ಯಾನಗರ",
      streetAddress: "Vidyanagar",
      city: "Hubli",
      state: "Karnataka",
      zip: "580021",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/v1Gz1a5R36etHVoY9",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Stress Management", "General Wellness"]
    },
    {
      id: 5,
      name: "Salmara Ayurveda - Mumbai",
      address: "Ghatkhopar - Mumbai",
      streetAddress: "Ghatkopar",
      city: "Mumbai",
      state: "Maharashtra",
      zip: "400075",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/UgViepQWXFDqHKWdA",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Pain Relief", "Digestive Health"]
    },
    {
      id: 6,
      name: "Salmara Ayurveda - Raichur",
      address: "Raichur / ರಾಯಚೂರು",
      streetAddress: "Raichur",
      city: "Raichur",
      state: "Karnataka",
      zip: "584101",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/mSogFZUFa53PZcFM6",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["General Wellness", "Pain Relief"]
    },
    {
      id: 7,
      name: "Salmara Ayurveda - Kozhikode",
      address: "Calicut - Kerala",
      streetAddress: "Calicut",
      city: "Kozhikode",
      state: "Kerala",
      zip: "673001",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/rtBx6qRTHyHQPTr86",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Stress Management", "Immunity"]
    },
    {
      id: 8,
      name: "Salmara Ayurveda - Kochi",
      address: "Kochi - Kerala",
      streetAddress: "Kochi",
      city: "Kochi",
      state: "Kerala",
      zip: "682001",
      country: "IN",
      googleMapsUrl: "https://maps.app.goo.gl/EaRZ3naE1KW4gz1x5",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "In-Person",
      specialties: ["Pain Relief", "Skin Care"]
    },
    {
      id: 10,
      name: "Salmara Virtual Clinic",
      address: "Online - Consultation",
      streetAddress: "Online",
      city: "Digital",
      state: "IN",
      zip: "000000",
      country: "IN",
      googleMapsUrl: "https://wa.me/919353436373",
      hours: "10:00 AM – 1:00 PM, 3:00 PM – 6:00 PM",
      availability: "Monday to Saturday",
      type: "Virtual",
      specialties: ["Immunity", "Skin Care", "Stress Management"]
    }
  ]
};
